---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:9.1.0
  amd64: ghcr.io/hassio-addons/debian-base/amd64:9.1.0
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Grafana"
  org.opencontainers.image.description: "The open platform for beautiful analytics and monitoring"
  org.opencontainers.image.source: "https://github.com/smalluniverse-net/home-assistant-addons"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.vendor: "smalluniverse-net"
